
from . import account_payment_register
from . import blood_bank
from . import blood_donation
from . import contra_indication
from . import doctor_allocation
from . import doctor_round
from . import doctor_slot
from . import doctor_specialization
from . import hospital_bed
from . import hospital_building
from . import hospital_degree
from . import hospital_family
from . import hospital_inpatient
from . import hospital_insurance
from . import hospital_laboratory
from . import hospital_outpatient
from . import hospital_pharmacy
from . import hospital_vaccination
from . import hospital_ward
from . import hr_employee
from . import inpatient_payment
from . import inpatient_surgery
from . import ir_attachment
from . import ir_ui_menu
from . import lab_medicine_line
from . import lab_test
from . import lab_test_line
from . import lab_test_result
from . import medicine_brand
from . import nursing_plan
from . import patient_lab_test
from . import patient_room
from . import pharmacy_medicine
from . import prescription_line
from . import product_template
from . import purchase_order
from . import res_partner
from . import res_users
from . import room_facility
from . import hospital_lab_test
from . import hospital_lab_result
from . import report_dashboard
from . import create_patient_wizard
from . import Company_fields
from . import company_isolated_config
from . import barcode_nomenclature
from . import account_move
from . import sale_order
