
{
    "name": "Hospital Management Odoo 17",
    "version": "17.0.1.0.9",
    "category": "Services",
    "summary": """This Module Helps to Manage Patients Records, Doctors Details,
     Lab Management , Employee Management etc.""",
    "description": """The hospital management module can be used to handle 
     the day-to-day activities of the hospital. Managing patient scheduling, 
     making patient ID cards, creating patient lab test results, and adding 
     doctors, patients, prescriptions, vaccines, etc. are all made easier 
     with the help of this module. This app offers a different dashboards for 
     different users.""",
    "author": "Cybrosys Techno Solutions",
    "company": "Cybrosys Techno Solutions",
    "maintainer": "Cybrosys Techno Solutions",
    "website": "https://www.cybrosys.com",
    "depends": ["website", "hr", "stock", "sale_management", "sale", "account", "purchase", "barcodes"],
    "data": [
        "security/base_hospital_management_groups.xml",
        "security/doctor_allocation_security.xml",
        "security/doctor_slot_security.xml",
        "security/patient_lab_test_security.xml",
        "security/ir.model.access.csv",
        "security/multi_company_security.xml",
        "security/purchase_multi_company_security.xml",
        "security/security_rule_updates.xml",
        "security/sale_inventory_multi_company_security.xml",
        "security/user_admin_access.xml",
        # "security/limited_user_manager_access.xml", 
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "data/website_data.xml",
        'data/prescription_time_data.xml',
        "data/hospital_charge_type_data.xml",
        "data/account_outstanding_accounts.xml",
        "views/menu_views.xml",
        "views/inpatient_surgery_views.xml",
        "views/hospital_bed_views.xml",
        "views/blood_bank_views.xml",
        "views/contra_indication_views.xml",
        "views/booking_success_templates.xml",
        "views/hospital_building_views.xml",
        "views/hospital_degree_views.xml",
        "views/doctor_allocation_views.xml",
        "views/hr_employee_views.xml",
        "views/hospital_inpatient_views.xml",
        "views/hospital_insurance_views.xml",
        "views/hospital_laboratory_views.xml",
        "views/patient_lab_test_views.xml",
        "views/lab_test_views.xml",
        "views/lab_test_result_views.xml",
        "views/medicine_brand_views.xml",
        "views/menu_views.xml",
        "views/hospital_outpatient_views.xml",
        "views/res_partner_views.xml",
        "views/patient_portal_templates.xml",
        "views/hospital_vaccination_views.xml",
        "views/product_template_views.xml",
        "views/room_facility_views.xml",
        "views/patient_card_templates.xml",
        "views/booking_success_templates.xml",
        "views/doctor_specialization_views.xml",
        "views/hospital_pharmacy_views.xml",
        "views/hospital_ward_views.xml",
        "views/stock_picking_views.xml",
        "views/patient_booking_templates.xml",
        "views/patient_room_views.xml",
        "views/lab_test_line_views.xml",
        "views/report_viewer_templates.xml",
        "report/res_partner_reports.xml",
        "views/report_sale_order_inherit.xml",
        "views/report_invoice_inherit.xml",
        # "views/invoice_hide_qty_tax.xml",
        "report/lab_test_line_reports.xml",
        # 'migrations/17.0.1.0.0/pre-migrate.py',
        # 'views/invoice_views.xml',
        'views/hospital_lab_test_views.xml',
        'views/hospital_lab_result_views.xml',
        'views/create_patient_wizard.xml',
        'views/Company_fields_view.xml',
        "views/prescription_line_views.xml",
        "views/purchase_order_views.xml",
        "views/company_isolated_config_views.xml",
        "views/hospital_charge_type_views.xml",
        "views/barcode_nomenclature_views.xml",
        # "views/user_manager_views.xml",
        # "views/user_manager_menu_views.xml",
        "views/settings_menu_views.xml",
        # "views/limited_user_manager_form.xml", 
        # "views/limited_user_manager_menu.xml",
        # "views/manager_menu.xml",
    ],
    "demo": ["demo/hr_job_demo.xml"],
    "assets": {
        "web.assets_frontend": [
            "base_hospital_management/static/src/js/prescription.js",
            "base_hospital_management/static/src/js/website_page.js",
        ],
        "web.assets_backend": [
            "base_hospital_management/static/src/css/doctor_dashboard.css",
            "base_hospital_management/static/src/css/reception_dashboard.css",
            "base_hospital_management/static/src/css/lab_dashboard.css",
            "base_hospital_management/static/src/css/pharmacy_dashboard.css",
            "base_hospital_management/static/src/css/report_dashboard.css",
            "base_hospital_management/static/src/xml/lab_dashboard_templates.xml",
            "base_hospital_management/static/src/xml/doctor_dashboard_templates.xml",
            "base_hospital_management/static/src/xml/report_dashboard_templates.xml",
            "base_hospital_management/static/src/js/lab_dashboard.js",
            "base_hospital_management/static/src/js/doctor_dashboard.js",
            "base_hospital_management/static/src/xml/pharmacy_orderlines.xml",
            "base_hospital_management/static/src/js/pharmacy_orderlines.js",
            "base_hospital_management/static/src/xml/pharmacy_dashboard_templates.xml",
            "base_hospital_management/static/src/js/pharmacy_dashboard.js",
            "base_hospital_management/static/src/js/report_dashboard.js",
            "base_hospital_management/static/src/xml/reception_dashboard_templates.xml",
            "base_hospital_management/static/src/js/reception_dashboard.js",
            "https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js",
        ],
    },
    "external_dependencies": {"python": ["python-barcode"]},
    "images": ["static/description/banner.jpg"],
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True,
}
